// Auto-generated by scripts/stamp-version.js
export const VERSION_INFO = {
    version: "1.0.0",
    gitSha: "d8e7f28e8c00ec3d059629da1ddc1140cbe652df",
    timestamp: "2026-02-10T01:04:01.344Z"
};
//# sourceMappingURL=version.js.map