/**
 * Test Run Type Definitions
 * 
 * Centralized types for test run and test execution data.
 * Exports Zod schemas for runtime validation and inferred TypeScript types.
 * 
 * ARCHITECTURE:
 * - Discriminated unions for different test states
 * - Server and client can share these schemas via z.infer<>
 * - Runtime validation prevents type mismatches across network boundaries
 */

import { z } from 'zod'

/**
 * Test execution status
 */
export const TestStatusSchema = z.enum([
  'pending',
  'running',
  'passed',
  'failed',
  'skipped',
  'error',
])
export type TestStatus = z.infer<typeof TestStatusSchema>

/**
 * Individual test case
 */
export const TestCaseSchema = z.object({
  id: z.string().min(1),
  name: z.string().min(1),
  file: z.string(),
  status: TestStatusSchema,
  duration: z.number().int().min(0),
  message: z.string().optional(),
  stack: z.string().optional(),
  metadata: z.record(z.string(), z.unknown()).optional(),
})

export type TestCase = z.infer<typeof TestCaseSchema>

/**
 * Test suite (collection of test cases)
 */
export const TestSuiteSchema = z.object({
  id: z.string(),
  name: z.string(),
  file: z.string(),
  status: TestStatusSchema,
  tests: z.array(TestCaseSchema),
  totalTests: z.number().int(),
  passedTests: z.number().int(),
  failedTests: z.number().int(),
  skippedTests: z.number().int(),
  duration: z.number().int(),
  metadata: z.record(z.string(), z.unknown()).optional(),
})

export type TestSuite = z.infer<typeof TestSuiteSchema>

/**
 * Code coverage data per file or overall
 */
export const CoverageSchema = z.object({
  file: z.string().optional().describe('File path; omit for overall coverage'),
  lines: z.number().min(0).max(100),
  branches: z.number().min(0).max(100).optional(),
  functions: z.number().min(0).max(100).optional(),
  statements: z.number().min(0).max(100).optional(),
})

export type Coverage = z.infer<typeof CoverageSchema>

/**
 * Test run status (top-level)
 */
export const TestRunStatusSchema = z.enum([
  'pending',      // Created but not started
  'running',      // Currently executing
  'completed',    // Finished successfully
  'failed',       // Finished with failures
  'cancelled',    // Cancelled before completion
  'error',        // Errored before tests could run
])
export type TestRunStatus = z.infer<typeof TestRunStatusSchema>

/**
 * Core Test Run object
 * Represents a single test execution across the codebase
 */
export const TestRunSchema = z.object({
  id: z.string().min(1),
  organizationId: z.string().uuid(),
  repositoryId: z.string(),
  
  // Metadata
  status: TestRunStatusSchema,
  title: z.string(),
  description: z.string().optional(),
  
  // Git context
  branch: z.string(),
  commitHash: z.string(),
  prNumber: z.number().int().optional(),
  
  // Execution
  startedAt: z.coerce.date().optional(),
  completedAt: z.coerce.date().optional(),
  durationMs: z.number().int().optional(),
  
  // Results
  suites: z.array(TestSuiteSchema).optional(),
  totalTests: z.number().int(),
  passedTests: z.number().int(),
  failedTests: z.number().int(),
  skippedTests: z.number().int(),
  
  // Coverage
  coverage: z.array(CoverageSchema).optional(),
  overallCoverage: CoverageSchema.optional(),
  coverageDelta: z.object({
    lines: z.number().optional(),
    branches: z.number().optional(),
    functions: z.number().optional(),
    statements: z.number().optional(),
  }).optional(),
  
  // Artifacts
  artifacts: z.array(z.object({
    name: z.string(),
    url: z.string().url(),
    type: z.enum(['test-report', 'coverage-report', 'log', 'html']),
  })).optional(),
  
  // Generation metadata
  generated: z.boolean().default(false).describe('Tests were generated by AI'),
  generatedTests: z.number().int().default(0),
  updatedTests: z.number().int().default(0),
  
  // Determinism & verification
  deterministic: z.boolean().optional().describe('Can be reproduced with same inputs'),
  signed: z.boolean().optional().describe('Cryptographically signed'),
  signatureHash: z.string().optional(),
  
  // Timestamps
  createdAt: z.coerce.date(),
  updatedAt: z.coerce.date(),
  
  // Additional metadata
  metadata: z.record(z.string(), z.unknown()).optional(),
})

export type TestRun = z.infer<typeof TestRunSchema>

/**
 * Test Run with execution details
 * This is what gets returned from the API
 */
export const TestRunDetailSchema = TestRunSchema.extend({
  suites: z.array(TestSuiteSchema),
  coverage: z.array(CoverageSchema),
})

export type TestRunDetail = z.infer<typeof TestRunDetailSchema>

/**
 * Minimal test run summary
 * For list views and dashboards
 */
export const TestRunSummarySchema = TestRunSchema.pick({
  id: true,
  status: true,
  branch: true,
  commitHash: true,
  prNumber: true,
  totalTests: true,
  passedTests: true,
  failedTests: true,
  overallCoverage: true,
  startedAt: true,
  completedAt: true,
  durationMs: true,
  generated: true,
})

export type TestRunSummary = z.infer<typeof TestRunSummarySchema>

/**
 * Paginated test run list response
 */
export const TestRunListSchema = z.object({
  data: z.array(TestRunSummarySchema),
  pagination: z.object({
    total: z.number().int(),
    limit: z.number().int(),
    offset: z.number().int(),
    hasMore: z.boolean(),
  }),
})

export type TestRunList = z.infer<typeof TestRunListSchema>

/**
 * Single test run API response
 */
export const TestRunApiResponseSchema = z.object({
  data: TestRunDetailSchema,
})

/**
 * Type guards for test run states
 */
export function isTestRunCompleted(run: TestRun): run is TestRun & { completedAt: Date } {
  return run.status === 'completed' || run.status === 'failed' || run.status === 'cancelled'
}

export function isTestRunRunning(run: TestRun): boolean {
  return run.status === 'pending' || run.status === 'running'
}

export function isTestRunFailed(run: TestRun): boolean {
  return run.status === 'failed' || run.status === 'error'
}

export function isTestRunSuccessful(run: TestRun): boolean {
  return run.status === 'completed' && run.failedTests === 0
}

/**
 * Coverage calculation helpers
 */
export function calculateCoverageDelta(
  current: Coverage,
  baseline: Coverage
): number {
  return current.lines - baseline.lines
}

export function isCoverageImproved(delta: number): boolean {
  return delta > 0
}

export function isCoverageDegraded(delta: number): boolean {
  return delta < 0
}

/**
 * Test run state machine helpers
 */
export function canCancelTestRun(status: TestRunStatus): boolean {
  return status === 'pending' || status === 'running'
}

export function canRetryTestRun(status: TestRunStatus): boolean {
  return status === 'failed' || status === 'error'
}

/**
 * Test Execution Results
 * Details about how a test was executed
 */
export const TestExecutionResultSchema = z.object({
  runId: z.string().uuid(),
  filePath: z.string(),
  framework: z.enum(['jest', 'mocha', 'pytest', 'vitest', 'other']),
  status: z.enum(['passed', 'failed', 'timeout']),
  testsPassed: z.number().int().min(0),
  testsFailed: z.number().int().min(0),
  totalTests: z.number().int().min(0),
  durationMs: z.number().int().min(0),
  meetsThreshold: z.boolean().describe('Coverage meets minimum threshold'),
  error: z.string().optional().describe('Error message if execution failed'),
  completedAt: z.coerce.date(),
})

export type TestExecutionResult = z.infer<typeof TestExecutionResultSchema>

/**
 * Coverage Metrics (detailed)
 */
export const CoverageMetricsSchema = z.object({
  lines: z.object({
    total: z.number().int().min(0),
    covered: z.number().int().min(0),
    percentage: z.number().min(0).max(100),
  }),
  branches: z.object({
    total: z.number().int().min(0),
    covered: z.number().int().min(0),
    percentage: z.number().min(0).max(100),
  }),
  functions: z.object({
    total: z.number().int().min(0),
    covered: z.number().int().min(0),
    percentage: z.number().min(0).max(100),
  }),
  statements: z.object({
    total: z.number().int().min(0),
    covered: z.number().int().min(0),
    percentage: z.number().min(0).max(100),
  }),
})

export type CoverageMetrics = z.infer<typeof CoverageMetricsSchema>

/**
 * File-level coverage
 */
export const FileCoverageSchema = z.object({
  file: z.string().describe('File path relative to repo root'),
  metrics: CoverageMetricsSchema,
  delta: z.object({
    lines: z.number().int().optional(),
    branches: z.number().int().optional(),
    functions: z.number().int().optional(),
    statements: z.number().int().optional(),
  }).optional(),
})

export type FileCoverage = z.infer<typeof FileCoverageSchema>

/**
 * Test Execution Request (for workers/background jobs)
 */
export const TestExecutionRequestSchema = z.object({
  runId: z.string().uuid(),
  repositoryId: z.string(),
  organizationId: z.string().uuid(),
  filePath: z.string(),
  testContent: z.string().describe('Generated or provided test code'),
  sourceCode: z.string().describe('Source code being tested'),
  framework: z.enum(['jest', 'mocha', 'pytest', 'vitest', 'other']),
  coverageThreshold: z.number().int().min(0).max(100).default(80),
  timeoutMs: z.number().int().min(100).default(30000),
})

export type TestExecutionRequest = z.infer<typeof TestExecutionRequestSchema>

/**
 * Test Execution Status (for job tracking)
 */
export const TestExecutionStatusSchema = z.enum([
  'queued',        // Waiting in queue
  'processing',    // Currently executing
  'completed',     // Successfully finished
  'failed',        // Failed to execute
  'timeout',       // Execution timeout
])

export type TestExecutionStatus = z.infer<typeof TestExecutionStatusSchema>

/**
 * Test Execution Job (for job queue)
 */
export const TestExecutionJobSchema = z.object({
  id: z.string().describe('Unique job ID'),
  runId: z.string().uuid(),
  repositoryId: z.string(),
  organizationId: z.string().uuid(),
  status: TestExecutionStatusSchema,
  result: TestExecutionResultSchema.optional(),
  createdAt: z.coerce.date(),
  startedAt: z.coerce.date().optional(),
  completedAt: z.coerce.date().optional(),
  retryCount: z.number().int().min(0).default(0),
  maxRetries: z.number().int().min(0).default(3),
})

export type TestExecutionJob = z.infer<typeof TestExecutionJobSchema>

/**
 * Batch Test Execution (multiple files)
 */
export const BatchTestExecutionSchema = z.object({
  runId: z.string().uuid(),
  repositoryId: z.string(),
  organizationId: z.string().uuid(),
  jobs: z.array(TestExecutionJobSchema),
  status: z.enum(['pending', 'running', 'completed', 'partial_failure']),
  summary: z.object({
    totalJobs: z.number().int(),
    completedJobs: z.number().int(),
    failedJobs: z.number().int(),
    successRate: z.number().min(0).max(100),
    totalDurationMs: z.number().int(),
  }),
  overallCoverage: CoverageMetricsSchema.optional(),
  completedAt: z.coerce.date().optional(),
})

export type BatchTestExecution = z.infer<typeof BatchTestExecutionSchema>

/**
 * Coverage metrics helper functions
 */
export function calculateOverallCoverage(fileCoverages: FileCoverage[]): CoverageMetrics {
  if (fileCoverages.length === 0) {
    return {
      lines: { total: 0, covered: 0, percentage: 0 },
      branches: { total: 0, covered: 0, percentage: 0 },
      functions: { total: 0, covered: 0, percentage: 0 },
      statements: { total: 0, covered: 0, percentage: 0 },
    };
  }

const aggregate = (key: 'lines' | 'branches' | 'functions' | 'statements'): { total: number; covered: number; percentage: number } => {
    const total = fileCoverages.reduce((sum, fc) => sum + (fc.metrics[key]?.total || 0), 0);
    const covered = fileCoverages.reduce((sum, fc) => sum + (fc.metrics[key]?.covered || 0), 0);
    const percentage = total > 0 ? (covered / total) * 100 : 0;
    return { total, covered, percentage };
  };

  return {
    lines: aggregate('lines'),
    branches: aggregate('branches'),
    functions: aggregate('functions'),
    statements: aggregate('statements'),
  };
}

export function isCoverageAboveThreshold(
  coverage: CoverageMetrics,
  threshold: number,
  metric: 'lines' | 'branches' | 'functions' | 'statements' = 'lines'
): boolean {
  return coverage[metric]?.percentage >= threshold;
}
