import { readdirSync, readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { resolve, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const repoRoot = resolve(fileURLToPath(new URL('..', import.meta.url)));
const migrationDir = resolve(repoRoot, 'supabase/migrations');
const outputDir = resolve(repoRoot, 'supabase/patches');
const outputPath = resolve(outputDir, 'rls-index-audit.sql');

const targets: Record<string, string[]> = {
  decision_runs: ['user_id', 'org_id', 'project_id', 'run_id', 'status', 'created_at'],
  traces: ['user_id', 'org_id', 'project_id', 'run_id', 'created_at', 'order_index'],
  approvals: ['user_id', 'org_id', 'project_id', 'run_id', 'status', 'created_at'],
  jobs: ['user_id', 'org_id', 'project_id', 'status', 'created_at', 'next_run_at'],
  orgs: ['user_id', 'org_id', 'created_at'],
  members: ['user_id', 'org_id', 'project_id', 'created_at'],
  api_keys: ['user_id', 'org_id', 'project_id', 'status', 'created_at'],
  usage: ['user_id', 'org_id', 'project_id', 'created_at'],
};

const sqlFiles = readdirSync(migrationDir)
  .filter((f) => f.endsWith('.sql'))
  .sort()
  .map((file) => readFileSync(join(migrationDir, file), 'utf8'));

const allSql = sqlFiles.join('\n');

function hasIndexed(table: string, column: string): boolean {
  const columnPattern = column.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
  const tablePattern = table.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
  const regex = new RegExp(`create\\s+index[\\s\\S]*?on\\s+\\w+\\.${tablePattern}\\s*\\(([^)]*)\\)`, 'gi');
  let match: RegExpExecArray | null;
  while ((match = regex.exec(allSql)) !== null) {
    if (new RegExp(`\\b${columnPattern}\\b`, 'i').test(match[1])) return true;
  }
  return false;
}

const missing: Array<{ table: string; column: string }> = [];
for (const [table, columns] of Object.entries(targets)) {
  for (const column of columns) {
    if (!hasIndexed(table, column)) missing.push({ table, column });
  }
}

mkdirSync(outputDir, { recursive: true });

const statements = missing.map(({ table, column }) =>
  `CREATE INDEX IF NOT EXISTS idx_${table}_${column} ON zeo.${table} (${column});`
);
const header = '-- Generated by scripts/rls-index-audit.ts\n-- Safe to apply multiple times (idempotent).\n';
writeFileSync(outputPath, `${header}${statements.join('\n')}\n`, 'utf8');

if (missing.length === 0) {
  console.log('[rls-index-audit] no missing indexes detected for target RLS tables.');
} else {
  console.log(`[rls-index-audit] missing indexes: ${missing.length}`);
  for (const item of missing) {
    console.log(` - zeo.${item.table} (${item.column})`);
  }
  console.log(`[rls-index-audit] generated patch: ${outputPath}`);
  console.log('[rls-index-audit] expected wins: faster RLS predicate evaluation and lower sequential scan pressure on hot queries.');
}

if (!process.env.DATABASE_URL) {
  console.log('[rls-index-audit] DATABASE_URL not configured; skipping EXPLAIN phase.');
}
