const fs = require('fs');
const path = require('path');
const { execSync } = require('child_process');

function getGitSha() {
    try {
        return execSync('git rev-parse HEAD').toString().trim();
    } catch (e) {
        return 'unknown';
    }
}

function getPackageVersion() {
    try {
        const pkg = require('../package.json');
        return pkg.version;
    } catch (e) {
        return '0.0.0';
    }
}

const sha = getGitSha();
const version = getPackageVersion();
const timestamp = new Date().toISOString();

const content = `// Auto-generated by scripts/stamp-version.js
export const VERSION_INFO = {
    version: "${version}",
    gitSha: "${sha}",
    timestamp: "${timestamp}"
};
`;

// Write to packages/core/src/version.ts
const targetPath = path.join(__dirname, '../packages/core/src/version.ts');
fs.writeFileSync(targetPath, content);

console.log(`Stamped version ${version} (${sha}) to ${targetPath}`);
